### ISSUE TITLE
Error on creating a new model 

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose#207]

**Comment by dilawar** [comment]
When trying to make a new model. These errors are caused when using the package available on OBS.                                                                               
   
```                                                                                                                  
ImportError: cannot import name write                                                                                  
                                                                                                                       
Traceback (most recent call last):                                                                                     
  File "mgui.py", line 1204, in newModelDialogSlot                                                                     
    self.setPlugin(plugin, modelRoot.path)                                                                             
  File "mgui.py", line 460, in setPlugin                                                                               
    self.plugin = self.loadPluginClass(str(name))(str(root), self)                                                     
  File "mgui.py", line 412, in loadPluginClass                                                                         
    pluginModule = self.loadPluginModule(name, re=re)                                                                  
  File "mgui.py", line 364, in loadPluginModule                                                                        
    module = imp.load_module(name, fp, pathname, description)                                                          
  File "/usr/lib/moose/gui/plugins/kkit.py", line 5, in <module>                                                       
    from moose.genesis import write                                                                                    
ImportError: cannot import name write 
```

                                                                                                                       
Importing xml file:                                                                                                    
                                                                                                                       
TypeError: cannot convert Shell to moose.Neutral. To get the existing object use `moose.element(obj)` instead.         

```                                                                                                               
Traceback (most recent call last):                                                                                     
  File "mgui.py", line 1106, in loadModelDialogSlot                                                                    
    ret,pluginName = self.checkPlugin(dialog)                                                                          
  File "mgui.py", line 1140, in checkPlugin                                                                            
    ret = loadFile(str(fileName),'%s' %(modelName),merge=False)                                                        
  File "/usr/lib/moose/gui/mload.py", line 133, in loadFile                                                            
    p = moose.Neutral(parent)                                                                                          
TypeError: cannot convert Shell to moose.Neutral. To get the existing object use `moose.element(obj)` instead.
```

**Comment by hrani** [comment]
This is because half and half package done in moose where latest moose-core taken but not moose-gui. New complete package should be made instead of fix this as a patch.
