### ISSUE TITLE
Doesn't install chemUtil

### ISSUE THREAD

**Issue by yurivict** [BhallaLab/moose#229]
It appears that this directory should have been installed ```moose-core/python/moose/chemUtil```, but it wasn't.

So, it fails:
```
Traceback (most recent call last):
  File "mgui.py", line 60, in <module>
    import mplugin
  File "/usr/local/lib/moose/gui/mplugin.py", line 49, in <module>
    import moose
  File "/usr/local/lib/python2.7/site-packages/moose/__init__.py", line 25, in <module>
    from .moose import *
  File "/usr/local/lib/python2.7/site-packages/moose/moose.py", line 20, in <module>
    import genesis.writeKkit
  File "/usr/local/lib/python2.7/site-packages/moose/genesis/__init__.py", line 1, in <module>
    from  .writeKkit import mooseWriteKkit
  File "/usr/local/lib/python2.7/site-packages/moose/genesis/writeKkit.py", line 16, in <module>
    from moose.chemUtil.chemConnectUtil import *
ImportError: No module named chemUtil.chemConnectUtil
```

**Comment by yurivict** [comment]
@dilawar Is there a way to fix this (and other bus)? It looks like some files aren't installed at all.

**Comment by hrani** [comment]
Quick fix, until Dilawar fix the installation script.
You could copy entire folder ‘chemUtil’ into
/usr/local/lib/python2.7/site-packages/moose/


Regards

Rani

**Comment by dilawar** [comment]
@yurivict Please try now. I've merged the lastest upstream `moose-core` module which contains the python binding. 
I can see the following being installed:

```
	debian/tmp/usr/lib/python2.7/dist-packages/moose/chemMerge/__init__.py
	debian/tmp/usr/lib/python2.7/dist-packages/moose/chemMerge/merge.py
	debian/tmp/usr/lib/python2.7/dist-packages/moose/chemMerge/mtypes.py
	debian/tmp/usr/lib/python2.7/dist-packages/moose/chemUtil/__init__.py
	debian/tmp/usr/lib/python2.7/dist-packages/moose/chemUtil/add_Delete_ChemicalSolver.py
	debian/tmp/usr/lib/python2.7/dist-packages/moose/chemUtil/chemConnectUtil.py
	debian/tmp/usr/lib/python2.7/dist-packages/moose/chemUtil/graphUtils.py
	debian/tmp/usr/lib/python2.7/dist-packages/moose/constants.py
```
It passing all tests on my machine. Lets hope it works for you as well.

**Comment by yurivict** [comment]
Thanks for fining this! It works beautifully!
I have created the FreeBSD port for MOOSE.

**Comment by dilawar** [comment]
Lovely. Send a PR.

⁣Sent from Blue ​
