### ISSUE TITLE
Connect BioModels/All Curated ModelIds fails: Exception: (307, u'Temporary Redirect')

### ISSUE THREAD

**Issue by yurivict** [BhallaLab/moose#230]
The progress indicator goes up to 13% and then throws this exception:

```
Traceback (most recent call last):
  File "/usr/local/lib/moose/gui/biomodelsclient.py", line 240, in runQuery
    name = unicode(self.client.service.getModelNameById(item)).encode("utf-8")
  File "/usr/local/lib/moose/gui/suds/client.py", line 521, in __call__
    return client.invoke(args, kwargs)
  File "/usr/local/lib/moose/gui/suds/client.py", line 581, in invoke
    result = self.send(soapenv)
  File "/usr/local/lib/moose/gui/suds/client.py", line 619, in send
    description=tostr(e), original_soapenv=original_soapenv)
  File "/usr/local/lib/moose/gui/suds/client.py", line 677, in process_reply
    raise Exception((status, description))
Exception: (307, u'Temporary Redirect')
```

**Comment by dilawar** [comment]
AFAIK, `suds` is not being maintained anymore. MOOSE uses `suds` to download the model. @hrani (and probably @subhacom )  might be able to comment on if there is plan to continue with suds to drop it altogether in favor of 'curl' or `urllib2` etc.

**Comment by subhacom** [comment]
`curl` or `urllib2` is not the same thing as `suds`, which is a SOAP client. There is a [fork of suds](https://bitbucket.org/jurko/suds) which has been maintained irregularly, and if anybody is willing to port the code, [zeep](http://docs.python-zeep.org/en/master/) might be a better alternative at present. 
However I wonder how many users are out there who might want this feature.

**Comment by dilawar** [comment]
Well, IMO either a feature should be maintained or removed. Let @hrani and @upibhalla take a call on this one. zeep looks promising; it depends only on `python-lxml` which is a well-maintained library and available on almost all linux flavors for which we build pacakges.

**Comment by hrani** [comment]
Yes I need to see zeep across the platform, if again not supported across
the platform not worth migrating. Will discuss with Upi and take a call.

**Comment by hrani** [comment]
Will check and let you know.

**Comment by dilawar** [comment]
@hrani Is they any update on this ticket?

**Comment by dilawar** [comment]
Pinging if there is update here.
