### ISSUE TITLE
Nightly package is failing to lauch gui

### ISSUE THREAD

**Issue by dilawar** [BhallaLab/moose#257]
Current nightly pack is failing to lauch gui.

```
[dilawars@ghevar _build (exprtk)]$ moosegui 
No CPU information available. Assuming single core.
No CPU information available. Assuming single core.
on node 0, numNodes = 1, numCores = 1
Traceback (most recent call last):
  File "mgui.py", line 82, in <module>
    from objectedit import ObjectEditDockWidget
  File "/usr/lib/moose/gui/objectedit.py", line 85, in <module>
    from moose.chemUtil.chemConnectUtil import getColor
ImportError: cannot import name getColor
```

**Comment by dilawar** [comment]
Nightly packages have removed `gui` from the packages.
